// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/shippy/vessel-service/proto/vessel/vessel.proto

package go_micro_srv_vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 每条货轮的熟悉
type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwerId               string   `protobuf:"bytes,6,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e32640d5aea549, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwerId() string {
	if m != nil {
		return m.OwerId
	}
	return ""
}

// 等待运送的货物
type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e32640d5aea549, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

// 货轮装得下的话
// 返回的多条货轮信息
type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_98e32640d5aea549, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	//
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	//
	FindAvailable(context.Context, *Specification, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func init() {
	proto.RegisterFile("src/shippy/vessel-service/proto/vessel/vessel.proto", fileDescriptor_98e32640d5aea549)
}

var fileDescriptor_98e32640d5aea549 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x05, 0x0a, 0x8c, 0xc1, 0xc3, 0x7a, 0x70, 0x83, 0x92, 0x34, 0x3d, 0x71, 0xb1, 0x24,
	0x10, 0x3f, 0xc0, 0x8b, 0x89, 0x1e, 0x8b, 0xd1, 0x23, 0x59, 0xb6, 0x23, 0x4c, 0x42, 0xbb, 0x9b,
	0xdd, 0xa6, 0xc0, 0xcf, 0xf8, 0xad, 0xc6, 0x5d, 0xc0, 0x60, 0x1a, 0x3d, 0xed, 0xec, 0x9b, 0x99,
	0x97, 0xf7, 0xde, 0xc0, 0xcc, 0x1a, 0x39, 0xb1, 0x6b, 0xd2, 0x7a, 0x3f, 0xa9, 0xd1, 0x5a, 0xdc,
	0xdc, 0x5b, 0x34, 0x35, 0x49, 0x9c, 0x68, 0xa3, 0x2a, 0x75, 0x00, 0x0f, 0x4f, 0xea, 0x30, 0x76,
	0xbd, 0x52, 0x69, 0x41, 0xd2, 0xa8, 0xd4, 0x9a, 0x3a, 0xf5, 0xad, 0xe4, 0x33, 0x80, 0xe8, 0xcd,
	0x95, 0xec, 0x0a, 0x42, 0xca, 0x79, 0x10, 0x07, 0xe3, 0x7e, 0x16, 0x52, 0xce, 0x86, 0xd0, 0x93,
	0x42, 0x0b, 0x49, 0xd5, 0x9e, 0x87, 0x71, 0x30, 0xee, 0x64, 0xa7, 0x3f, 0x1b, 0x01, 0x14, 0x62,
	0xb7, 0xd8, 0x22, 0xad, 0xd6, 0x15, 0x6f, 0xb9, 0x6e, 0xbf, 0x10, 0xbb, 0x77, 0x07, 0x30, 0x06,
	0xed, 0x52, 0x14, 0xc8, 0xdb, 0x8e, 0xcc, 0xd5, 0xec, 0x0e, 0xfa, 0xa2, 0x16, 0xb4, 0x11, 0xcb,
	0x0d, 0xf2, 0x4e, 0x1c, 0x8c, 0x7b, 0xd9, 0x0f, 0xc0, 0x6e, 0xa0, 0xab, 0xb6, 0x68, 0x16, 0x94,
	0xf3, 0xc8, 0x2d, 0x45, 0xdf, 0xdf, 0xe7, 0x3c, 0x79, 0x81, 0xc1, 0x5c, 0xa3, 0xa4, 0x0f, 0x92,
	0xa2, 0x22, 0x55, 0x9e, 0xc9, 0x0a, 0xfe, 0x94, 0x15, 0xfe, 0x92, 0x95, 0xd4, 0xd0, 0xcb, 0xd0,
	0x6a, 0x55, 0x5a, 0x64, 0x33, 0x88, 0x7c, 0x04, 0x8e, 0xe4, 0x72, 0x7a, 0x9b, 0x36, 0xc4, 0x93,
	0xfa, 0x68, 0xb2, 0xc3, 0x28, 0x7b, 0x80, 0xae, 0xaf, 0x2c, 0x0f, 0xe3, 0xd6, 0x7f, 0x5b, 0xc7,
	0xd9, 0x29, 0xc2, 0xc0, 0x43, 0x73, 0x7f, 0x24, 0xf6, 0x0a, 0x83, 0x27, 0x2a, 0xf3, 0xc7, 0x93,
	0xfd, 0xa4, 0x91, 0xe7, 0xcc, 0xf8, 0x70, 0xd4, 0x38, 0x73, 0x34, 0x94, 0x5c, 0x2c, 0x23, 0x77,
	0xe7, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x2f, 0x65, 0x00, 0x1e, 0x02, 0x00, 0x00,
}
